#!/bin/bash
# by Dominik Stanisław Suchora <suchora.dominik7@gmail.com>
# License: GNU GPLv3

shopt -s extglob

declare maxprocs='1' url _cookies old nousers='0' noreactions='0'

IFS=$'\n'

ucurl() {
    curl -k -L -g -m 120 -s -b "$_cookies" -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.15.2 Chrome/87.0.4280.144 Safari/537.36" -H "Accept-Encoding: gzip, deflate" --compressed "$@"
}

get_user() {
    [ -z "$1" ] && return
    [[ "$1" =~ ^http[s]?://([[:alnum:]-]+\.)+[[:alpha:]]+/(.*[./])?([[:digit:]]+)/[\&?]tooltip=true\&.*$ ]] || { echo "improper url - $1" >&2; return; }
    local -r id="${BASH_REMATCH[3]}"
    [ -e "m-$id" ] && return
    echo "$1" >&2
    local -r t="$(ucurl -b "$2" "$1" | jq -r '.html.content')"
    local background

    {
    background="$(sed -n '/<div class="memberProfileBanner memberTooltip-header.*url(/{s#.*url(##;s#^/[^/]#'"$url"'\0#;s#^//#https://#;s/?.*//;p;q}' <<< "$t")"
    echo "{\"id\":$id,\"background\":\"$background\"}"
    reliq '
        .location a href=b>/misc/location-info | "%i",
        .avatar img src | "%(src)v" / sed "s#^/[^/]#'"$url"'\0#;s#^//#https://#;s/?.*//; q",
        .joined dl .pairs .pairs--inline m@">Joined<"; time datetime | "%(datetime)v",
        .lastseen dl .pairs .pairs--inline m@">Last seen<"; time datetime | "%(datetime)v",
        .title span .userTitle | "%i",
        .name h4 .memberTooltip-name; a; * c@[0] | "%i",
        .forum em; a href | "%(href)v",
        .messages dl m@"<dt>Messages</dt>"; dd; * c@[0] | "%i\n" / sed "/[0-9]/{s/[,\t ]//g;p;q}" "n" tr "\n",
        .reactionscore dl m@B>"<dt.*>Reaction.*</dt>"; dd; * c@[0] | "%i\n" / sed "/[0-9]/{s/[,\t ]//g;p;q}" "n" tr "\n",
        .points dl m@B>"<dt .*title=\".*\">Points</dt>"; dd; * c@[0] | "%i\n" / sed "/[0-9]/{s/[,\t ]//g;p;q}" tr "\n"
    ' <<< "$t"
    } | jq -srcM '.[0]+.[1]' > "m-$id"
}

get_thread() {
    [[ "$1" =~ ^http[s]?://([[:alnum:]-]+\.)+[[:alpha:]]+/(.*[./])?([[:digit:]]+)(/.*)?$ ]] || { echo "improper url - $1"; return; }
    local -r id="${BASH_REMATCH[3]}"
    [ -e "$id" ] && return
    echo "$1" >&2
    local t="$(ucurl -D- "$1")"
    local t2 cookies url_first_delimiter='?'
    [ -z "${1##*\?*}" ] && url_first_delimiter='&'
    cookies="$(sed -n '/^<!DOCTYPE html>/q; /^[sS]et-[cC]ookie: /{s/Set-Cookie: //i;p}' <<< "$t" | sed ':x;s/\r//g;$!{N;s/\n/\;/;bx}')"
    local next

    {
    echo "{\"link\":\"$1\",\"id\":$id}"
    reliq '
        .title h1 {
            h1 .p-title-value | "%i\n",
            h1 qid="page-header" | "%i\n",
            h1 .MessageCard__thread-title | "%i\n"
        } / sed ":x; s/<[^>]*>//g; $!{N;s/\n/ /;bx}",

        div .p-description; {
            .user_id.u * data-user-id | "%(data-user-id)v",
            .user * data-user-id; * c@[0] | "%i",
            .date time datetime | "%(datetime)v",
        },
        .path.a ul .p-breadcrumbs -.p-breadcrumbs--bottom; span | "%i\n",
        .tags.a("|") a class=b>tagItem | "%i\n" / sed ":x; s/\t//g; /^$/d; $!{N;s/\n/|/;bx}; s/|$//; s/|\+/|/g" tr "\n",
        .poll form data-xf-init="poll-block ajax-submit"; {
            .title h2 .block-header | "%i\n" / sed "s/\t//g; s/<[^>]*>//g; s/^ *//; s/ *$//; /^$/d;",
            .answers li; {
                .option h3 .pollResult-response | "%i",
                .votes.u span .pollResult-votes | "%i" / sed "s/\t//g; s/<[^>]*>//g; s/^ *//; s/ *$//; /^$/d; s/^.* //"
            } |
        }' <<< "$t"
    local xfToken="$(reliq 'html data-csrf | "%(data-csrf)v\n"' <<< "$t")"
    [ -z "$xfToken" ] && xfToken="$(reliq 'input name="_xfToken" value | "%(value)v\n" / line [1]' <<< "$t")" && \
    [ -z "$xfToken" ] && xfToken="$(sed -n "/^[ \t]*csrf: '[0-9]*,[a-f0-9]*',/{s/.*: '//;s/'.*//;p;q}" <<< "$t")"

    while :
    do
        for i in $([ -z "$next" ] && tr -d '\r\n\t\a' <<< "$t" |  reliq 'div #thread-main-section; div .MessageCard l@[1] | "%i\n"') $(tr -d '\r\n\t\a' <<< "$t" | reliq 'article id, div #B>post-[0-9]*, div .block-container; div .MessageCard | "%i\n"')
        do
            {
            reliq '
                .user_id.u {
                    h4 class=b>message-name; * data-user-id | "%(data-user-id)v",
                    div .MessageCard__avatar; a data-user-id | "%(data-user-id)v"
                },

                .user {
                    h4 class=b>message-name; * c@[0] | "%i",
                    * .MessageCard__user-info__name; * c@[0] | "%i"
                },

                .id.u E>(span|div) #B>post-[0-9]* | "%(id)v" / sed "s/^post-//;q",

                .date {
                    * class=b>message-attribution-main; time datetime | "%(datetime)v",
                    * .MessageCard__date-created; [0] time datetime .u-dt | "%(datetime)v"
                },

                .text {
                    article class=b>message-body; div .bbWrapper | "%i",
                    div .MessageCard__content-inner; div .bbWrapper | "%i"
                },

                .attachments.a {
                    ul .attachmentList | "%i\n",
                    div #signature-content-wrapper; div .bbWrapper | "%i\n"
                }
            ' <<< "$i"

            [ "$nousers" -eq '0' ] && get_user "$(reliq 'h4 class=b>message-name; a data-user-id href | "'"$url"'%(href)v'"$url_first_delimiter"'tooltip=true&_xfWithData=1&_xfToken='"$xfToken"'&_xfResponseType=json\n", div .MessageCard__avatar; a data-user-id href | "'"$url"'%(href)v'"$url_first_delimiter"'tooltip=true&_xfWithData=1&_xfToken='"$xfToken"'&_xfResponseType=json\n"' <<< "$i")" "$cookies"

            if [ "$noreactions" -eq '0' ]
            then
                t2="$(reliq 'a .reactionsBar-link href | "'"$url"'%(href)v\n"' <<< "$i")"
                if [ -n "$t2" ] #reactions
                then
                    t2="$t2${url_first_delimiter}_xfRequestUri=&_xfWithData=1&_xfToken=$xfToken&_xfResponseType=json"
                    echo "$t2" >&2
                    ucurl -b "$cookies" "$t2" | jq -r '.html.content' | tr -d '\n\t' | reliq '.reactions div .contentRow; {
                        .user_id.u * .username data-user-id | "%(data-user-id)v",
                        .user * .username data-user-id; * c@[0] | "%i",
                        .date time .u-dt datetime | "%(datetime)v",
                        .reaction span .reaction; img title | "%(title)v"
                    } |'
                else
                    echo '{"reactions":[]}'
                fi
            else
                echo '{"reactions":[]}'
            fi
            } | jq -srcM '.[0] + .[1]'
        done

        next="$(reliq 'div .block-outer; a .pageNav-jump .pageNav-jump--next href | "'"$url"'%(href)v\n" / line [1]' <<< "$t")"
        grep -Eq '/page-[0-9]*(\?.*)?/?(#.*)?$' <<< "$next" || break
        echo "$next" >&2
        t="$(ucurl -b "$cookies" "$next")"
    done
    } | jq -srcM '.[2:] as $posts | .[0] + .[1] | .["posts"]=$posts' > "$id"
}

get_category() {
    for i in $(reliq '* .node-title; a href -href=b>/link-forums/ | "'"$url"'%(href)v\n"' <&0)
    do
        get_forum "$i"
    done
}

get_forum() {
    local t next
    echo "$1" >&2
    t="$(ucurl "$1")"
    while :
    do
        for j in $(reliq '* .structItem-title; a href | "'"$url"'%(href)v\n"' <<< "$t")
        do
            [ "$(jobs | wc -l)" -gt "$maxprocs" ] && wait %%
            get_thread "$j" &
        done

        next="$(reliq 'div .block-outer; a .pageNav-jump .pageNav-jump--next href | "'"$url"'%(href)v\n" / line [1]' <<< "$t")"
        grep -Eq '/page-[0-9]*(\?.*)?/?(#.*)?$' <<< "$next" || break
        echo "$next" >&2
        t="$(ucurl "$next")"
    done
    get_category <<< "$t"
}

get_tag() {
    local t next
    echo "$1" >&2
    t="$(ucurl "$1")"
    while :
    do
        for j in $(reliq 'div class=b>contentRow; a href -data-user-id | "'"$url"'%(href)v\n"' <<< "$t")
        do
            [ "$(jobs | wc -l)" -gt "$maxprocs" ] && wait %%
            get_thread "$j" &
        done

        next="$(reliq 'div .block-outer .block-outer--after; a .pageNav-jump .pageNav-jump--next href | "'"$url"'%(href)v\n"' <<< "$t")"
        grep -q '/page-[0-9]*$' <<< "$next" || break
        echo "$next" >&2
        t="$(ucurl "$next")"
    done
}

get_old_thread() {
    [[ "$1" =~ ^http[s]?://([[:alnum:]-]+\.)+[[:alpha:]]+/(.*[./])?([[:digit:]]+)[/]?$ ]] || { echo "improper url - $1"; return; }
    local -r id="${BASH_REMATCH[3]}"
    [ -e "$id" ] && return
    echo "$1" >&2
    local t="$(ucurl "$1")" t2 next messageUserBlock avatar

    {
    echo "{\"link\":\"$1\",\"id\":\"$id\"}"
    reliq '
        .title { div class=b>titleBar; h1 | "%i", div #header; h1 | "%i" / sed ":x; s/<[^>]*>//g; $!{N;s/\n/ /;bx}" },
        p #pageDescription; {
            .user_id.u a .username href | "%(href)v" / sed "s/^.*[\/.]\([0-9]\+\)/\1/; s/[^0-9]$//",
            .user a .username | "%i",
            .date * .DateTime | "%i"
        },
        .path.a span .crumbs; span itemprop=B>"[a-z]*"; * c@[0] | "%i\n",
        .tags.a("|") ul .tagList; a .tag | "%i|" / sed "s/<[^>]*>[^<]*<\/[^>]*>//g; s/|$//"
    ' <<< "$t"

    while :
    do
        for i in $(tr -d '\n\t' <<< "$t" | reliq 'ol #messageList; li #E>post-[0-9]* data-author l@[1]')
        do
            {
            messageUserBlock="$(reliq 'div class=b>messageUserBlock | "%i\n"' <<< "$i")"
            avatar="$(reliq '* class=b>avatar; img src | "'"$url"'/%(src)v\n" / line [1]' <<< "$messageUserBlock")"
            if [ -z "$avatar" ]
            then
                reliq '
                    .user_id.u span class="img m" style | "%(style)v" / sed "s#^.*/avatars/m/[0-9]*/##; s#\..*##",
                    .avatar span class="img m" style | "'"$url"'%(style)v" / sed "s/?[0-9]*'\'')//; s/background-image: url('\''/\//; s/'\'')$//"
                ' <<< "$messageUserBlock"
            else
                t2=""
                [[ "$avatar" =~ /([[:digit:]]*)\.[[:alpha:]]*?(\?.*)$ ]] && t2="${BASH_REMATCH[1]}"
                echo "{\"user_id\":\"$t2\",\"avatar\":\"${avatar%\?[[:digit:]]*}\"}"
            fi
            reliq '
            h3 .userText; {
                .user_title em class=b>userTitle | "%i",
                .user_banner em class=b>userBanner; * c@[0] | "%i" / sed "/^[ \t]*$/d",
            },
            .user_extra dl; {
                .name dt; * c@[0] | "%i",
                .value dd; * c@[0] | "%i"
            } |' <<< "$messageUserBlock"
            reliq '
                .user li data-author l@[0] | "%(data-author)v",
                .id.u li data-author l@[0] #B>post-[0-9]* | "%(id)v" / sed "s/^post-//",
                .text div .messageContent; article | "%i"' <<< "$i"
            } | jq -srcM '.[0] + .[1] + .[2]'
        done

        next="$(reliq 'nav; a class href=Be>"/page-[0-9]*" m@B>"^[^0-9]*&gt;" | "'"$url"'/%(href)v\n" / line [-]' <<< "$t")"
        grep -q '/page-[0-9]*$' <<< "$next" || break
        echo "$next" >&2
        t="$(ucurl "$next")"
    done
    } | jq -srcM '.[2:] as $posts | .[0] + .[1] | .["posts"]=$posts' > "$id"
}

get_old_category() {
    for i in $(reliq 'h3 .nodeTitle; a -href=B>".\?#.*" href | "'"$url"'/%(href)v\n"' <&0)
    do
        get_old_forum_tag "$i"
    done
}

get_old_forum_tag() {
    local t next
    echo "$1" >&2
    t="$(ucurl "$1")"
    while :
    do
        for j in $(reliq 'li id; div .titleText; h3 .title; a href | "'"$url"'/%(href)v\n"' <<< "$t")
        do
            [ "$(jobs | wc -l)" -gt "$maxprocs" ] && wait %%
            get_old_thread "$j" &
        done

        next="$(reliq 'nav; a class href=Be>"/page-[0-9]*" m@B>"^[^0-9]*&gt;" | "'"$url"'/%(href)v\n" / line [-]' <<< "$t")"
        grep -q '/page-[0-9]*$' <<< "$next" || break
        echo "$next" >&2
        t="$(ucurl "$next")"
    done
    get_old_category <<< "$t"
}

baseurl() {
    [[ "$1" =~ ^(http[s]?://([[:alnum:]-]+\.)+[[:alpha:]]+)(/.*)?$ ]] && echo "${BASH_REMATCH[1]}"
}

usage() {
    printf '%s [OPTION]... [URL]...\n' "${0##*/}"
    printf 'Download, convert to json and save xenforo forums from URL.\n\n'
    printf 'Options:\n  -d,\t--dir DIR\t\tchange directory to DIR\n'
    printf '  -p,\t--max-procs NUM\t\tset number of processes to run at a time\n'
    printf '  -b,\t--cookie DATA|FILENAME\tpass cookie to curl\n'
    printf '  -t,\t--thread URL\t\tpass URL as thread link\n'
    printf '  -T,\t--tag URL\t\tpass URL as tag link\n'
    printf '  -f,\t--forum URL\t\tpass URL as forum link\n'
    printf '  -c,\t--category URL\t\tpass URL as category link, can be used to download the whole forum\n'
    printf '  -o,\t--old\t\t\tuse old format\n'
    printf '  -n,\t--no-reactions\t\tdo not download reactions to posts\n'
    printf '  -N,\t--no-users\t\tdo not download users\n'
    printf '  -h,\t--help\t\t\tshow this message\n'
}

[ "$#" -eq 0 ] && { usage >&2; exit 1; }

while [ "$#" -gt 0 ]
do
    case "$1" in
        -d|--dir) cd "$2" || break; shift;;
        -t|--thread)
            url="$(baseurl "$2")"
            if [ -n "$old" ]
            then
                get_old_thread "$2"
            else
                get_thread "$2"
            fi
            shift;;
        -f|--forum)
            url="$(baseurl "$2")"
            if [ -n "$old" ]
            then
                get_old_forum_tag "$2"
            else
                get_forum "$2"
            fi
            shift;;
        -T|--tag)
            url="$(baseurl "$2")"
            if [ -n "$old" ]
            then
                get_old_forum_tag "$2"
            else
                get_tag "$2"
            fi
            shift;;
        -c|--category)
            url="$(baseurl "$2")"
            if [ -n "$old" ]
            then
                ucurl "$2" | get_old_category "$2"
            else
                ucurl "$2" | get_category "$2"
            fi
            shift;;
        -b|--cookie) _cookies="$2"; shift;;
        -p|--max-procs) maxprocs="$2"; shift;;
        -o|--old) old='1';;
        -n|--no-reactions) noreactions='1';;
        -N|--no-users) nousers='1';;
        -h|--help) usage >&2; exit;;
        -*) usage >&2; exit 1;;
        *) break;;
    esac
    shift
done

while [ "$#" -gt 0 ]
do
    url="$(baseurl "$1")"
    case "$1" in
        http?(s)://+(+([[:alnum:]-]).)+([[:alpha:]])/?(*[/?])@(thread?(s)|topic?(s))/*)
            if [ -n "$old" ]
            then
                get_old_thread "$1"
            else
                get_thread "$1"
            fi;;
        http?(s)://+(+([[:alnum:]-]).)+([[:alpha:]])/?(*[/?])forum?(s)/*)
            if [ -n "$old" ]
            then
                get_old_forum_tag "$1"
            else
                get_forum "$1"
            fi;;
        http?(s)://+(+([[:alnum:]-]).)+([[:alpha:]])/?(*[/?])tag?(s)/*)
            if [ -n "$old" ]
            then
                get_old_forum_tag "$1"
            else
                get_tag "$1"
            fi;;
        *)
            if [ -n "$old" ]
            then
                ucurl "$1" | get_old_category
            else
                ucurl "$1" | get_category
            fi;;
    esac
    shift
done
